; In balanced ternary
(assert-equal (fib-bal3 '(    0)) '(        0))
(assert-equal (fib-bal3 '(    +)) '(        +))
(assert-equal (fib-bal3 '(  + -)) '(        +))
(assert-equal (fib-bal3 '(  + 0)) '(      + -))
(assert-equal (fib-bal3 '(  + +)) '(      + 0))
(assert-equal (fib-bal3 '(+ - -)) '(    + - -))
(assert-equal (fib-bal3 '(+ - 0)) '(    + 0 -))
(assert-equal (fib-bal3 '(+ - +)) '(    + + +))
(assert-equal (fib-bal3 '(+ 0 -)) '(  + - + 0))
(assert-equal (fib-bal3 '(+ 0 0)) '(  + + - +))
(assert-equal (fib-bal3 '(+ 0 +)) '(+ - 0 0 +))
(assert-equal (fib-bal3 '(+ + -)) '(+ 0 + 0 -))
; In binary
(assert-equal (fib-bin '(         ())) '(                  ()))
(assert-equal (fib-bin '(          t)) '(                   t))
(assert-equal (fib-bin '(       t ())) '(                   t))
(assert-equal (fib-bin '(       t  t)) '(                t ()))
(assert-equal (fib-bin '(    t () ())) '(                t  t))
(assert-equal (fib-bin '(    t ()  t)) '(             t ()  t))
(assert-equal (fib-bin '(    t  t ())) '(          t () () ()))
(assert-equal (fib-bin '(    t  t  t)) '(          t  t ()  t))
(assert-equal (fib-bin '( t () () ())) '(       t ()  t ()  t))
(assert-equal (fib-bin '( t () ()  t)) '(    t () () ()  t ()))
(assert-equal (fib-bin '( t ()  t ())) '(    t  t ()  t  t  t))
(assert-equal (fib-bin '( t ()  t  t)) '( t ()  t  t () ()  t))
