; Tests of balanced-ternary arithmetic.
;
; Aaron Mansheim, 2011-09-26

; tests of trit-add-carrying x y c
(assert-equal (trit-add '- '- '-) '(- 0))
(assert-equal (trit-add '- '- '0) '(- +))
(assert-equal (trit-add '- '0 '-) '(- +))
(assert-equal (trit-add '0 '- '-) '(- +))
(assert-equal (trit-add '- '- '+) '(0 -))
(assert-equal (trit-add '- '0 '0) '(0 -))
(assert-equal (trit-add '- '+ '-) '(0 -))
(assert-equal (trit-add '0 '- '0) '(0 -))
(assert-equal (trit-add '0 '0 '-) '(0 -))
(assert-equal (trit-add '+ '- '-) '(0 -))
(assert-equal (trit-add '- '0 '+) '(0 0))
(assert-equal (trit-add '- '+ '0) '(0 0))
(assert-equal (trit-add '0 '- '+) '(0 0))
(assert-equal (trit-add '0 '0 '0) '(0 0))
(assert-equal (trit-add '0 '+ '-) '(0 0))
(assert-equal (trit-add '+ '0 '-) '(0 0))
(assert-equal (trit-add '+ '- '0) '(0 0))
(assert-equal (trit-add '- '+ '+) '(0 +))
(assert-equal (trit-add '0 '0 '+) '(0 +))
(assert-equal (trit-add '0 '+ '0) '(0 +))
(assert-equal (trit-add '+ '- '+) '(0 +))
(assert-equal (trit-add '+ '0 '0) '(0 +))
(assert-equal (trit-add '+ '+ '-) '(0 +))

; tests of bal3-trits-add
(assert-equal (bal3-trits-add '- '- '(- s)) '(- 0 s))
(assert-equal (bal3-trits-add '- '- '(0 s)) '(- + s))
(assert-equal (bal3-trits-add '- '0 '(- s)) '(- + s))
(assert-equal (bal3-trits-add '0 '- '(- s)) '(- + s))
(assert-equal (bal3-trits-add '- '- '(+ s)) '(0 - s))
(assert-equal (bal3-trits-add '- '0 '(0 s)) '(0 - s))
(assert-equal (bal3-trits-add '- '+ '(- s)) '(0 - s))
(assert-equal (bal3-trits-add '0 '- '(0 s)) '(0 - s))
(assert-equal (bal3-trits-add '0 '0 '(- s)) '(0 - s))
(assert-equal (bal3-trits-add '+ '- '(- s)) '(0 - s))
(assert-equal (bal3-trits-add '- '0 '(+ s)) '(0 0 s))
(assert-equal (bal3-trits-add '- '+ '(0 s)) '(0 0 s))
(assert-equal (bal3-trits-add '0 '- '(+ s)) '(0 0 s))
(assert-equal (bal3-trits-add '0 '0 '(0 s)) '(0 0 s))
(assert-equal (bal3-trits-add '0 '+ '(- s)) '(0 0 s))
(assert-equal (bal3-trits-add '+ '0 '(- s)) '(0 0 s))
(assert-equal (bal3-trits-add '+ '- '(0 s)) '(0 0 s))
(assert-equal (bal3-trits-add '- '+ '(+ s)) '(0 + s))
(assert-equal (bal3-trits-add '0 '0 '(+ s)) '(0 + s))
(assert-equal (bal3-trits-add '0 '+ '(0 s)) '(0 + s))
(assert-equal (bal3-trits-add '+ '- '(+ s)) '(0 + s))
(assert-equal (bal3-trits-add '+ '0 '(0 s)) '(0 + s))
(assert-equal (bal3-trits-add '+ '+ '(- s)) '(0 + s))

(assert-equal (bal3-add '(0) '(-)) '(-))
(assert-equal (bal3-add '(+ 0) '(0 -)) '(+ -))
(assert-equal (bal3-add '(+ - - 0) '(+ 0 - -)) '(+ + + -))
(assert-equal (bal3-neg '(+ - - 0)) '(- + + 0))
(assert-equal (bal3-neg '(- + + - 0 0 0 - + + -))
                        '(+ - - + 0 0 0 + - - +))
(assert-equal (bal3-minus '(+ - - 0) '(+ 0 - -)) '(- 0 +))

(assert-equal (bin-pred '(        ())) '(      ()))
(assert-equal (bin-pred '(         t)) '(      ()))
(assert-equal (bin-pred '(      t ())) '(       t))
(assert-equal (bin-pred '(      t  t)) '(    t ()))
(assert-equal (bin-pred '(   t () ())) '(    t  t))
(assert-equal (bin-pred '(   t ()  t)) '( t () ()))
(assert-equal (bin-pred '(   t  t ())) '( t ()  t))
(assert-equal (bin-pred '(   t  t  t)) '( t  t ()))
(assert-equal (bin-pred '(t () () ())) '( t  t  t))

(assert-equal (dec-add '(0) '(1)) '(1))
(assert-equal (dec-add '(3) '(1)) '(4))
(assert-equal (dec-add '(1 5) '(2 3)) '(3 8))
(assert-equal (dec-add '(1 5) '(2 8)) '(4 3))
