; Tests of balanced-ternary arithmetic.
;
; Aaron Mansheim, 2011-09-26

;(assert-equal (trit_add- '- '-) '(- 0))
;(assert-equal (trit_add- '- '0) '(- +))
;(assert-equal (trit_add- '0 '-) '(- +))
;(assert-equal (trit_add  '- '-) '(- +))
;(assert-equal (trit_add- '- '+) '(0 -))
;(assert-equal (trit_add- '0 '0) '(0 -))
;(assert-equal (trit_add- '+ '-) '(0 -))
;(assert-equal (trit_add  '- '0) '(0 -))
;(assert-equal (trit_add  '0 '-) '(0 -))
;(assert-equal (trit_add+ '- '-) '(0 -))
;(assert-equal (trit_add- '0 '+) '(0 0))
;(assert-equal (trit_add- '+ '0) '(0 0))
;(assert-equal (trit_add  '- '+) '(0 0))
;(assert-equal (trit_add  '0 '0) '(0 0))
;(assert-equal (trit_add  '+ '-) '(0 0))
;(assert-equal (trit_add+ '- '0) '(0 0))
;(assert-equal (trit_add+ '0 '-) '(0 0))
;(assert-equal (trit_add- '+ '+) '(0 +))
;(assert-equal (trit_add  '0 '+) '(0 +))
;(assert-equal (trit_add  '+ '0) '(0 +))
;(assert-equal (trit_add+ '- '+) '(0 +))
;(assert-equal (trit_add+ '0 '0) '(0 +))
;(assert-equal (trit_add+ '+ '-) '(0 +))
;(assert-equal (trit_add  '+ '+) '(+ -))
;(assert-equal (trit_add+ '0 '+) '(+ -))
;(assert-equal (trit_add+ '+ '0) '(+ -))
;(assert-equal (trit_add+ '+ '+) '(+ 0))

; tests of trit_add_carrying x y c
(assert-equal (trit_add '- '- '-) '(- 0))
(assert-equal (trit_add '- '- '0) '(- +))
(assert-equal (trit_add '- '0 '-) '(- +))
(assert-equal (trit_add '0 '- '-) '(- +))
(assert-equal (trit_add '- '- '+) '(0 -))
(assert-equal (trit_add '- '0 '0) '(0 -))
(assert-equal (trit_add '- '+ '-) '(0 -))
(assert-equal (trit_add '0 '- '0) '(0 -))
(assert-equal (trit_add '0 '0 '-) '(0 -))
(assert-equal (trit_add '+ '- '-) '(0 -))
(assert-equal (trit_add '- '0 '+) '(0 0))
(assert-equal (trit_add '- '+ '0) '(0 0))
(assert-equal (trit_add '0 '- '+) '(0 0))
(assert-equal (trit_add '0 '0 '0) '(0 0))
(assert-equal (trit_add '0 '+ '-) '(0 0))
(assert-equal (trit_add '+ '0 '-) '(0 0))
(assert-equal (trit_add '+ '- '0) '(0 0))
(assert-equal (trit_add '- '+ '+) '(0 +))
(assert-equal (trit_add '0 '0 '+) '(0 +))
(assert-equal (trit_add '0 '+ '0) '(0 +))
(assert-equal (trit_add '+ '- '+) '(0 +))
(assert-equal (trit_add '+ '0 '0) '(0 +))
(assert-equal (trit_add '+ '+ '-) '(0 +))

; tests of bal3_trits_add
(assert-equal (bal3_trits_add '- '- '(- s)) '(- 0 s))
(assert-equal (bal3_trits_add '- '- '(0 s)) '(- + s))
(assert-equal (bal3_trits_add '- '0 '(- s)) '(- + s))
(assert-equal (bal3_trits_add '0 '- '(- s)) '(- + s))
(assert-equal (bal3_trits_add '- '- '(+ s)) '(0 - s))
(assert-equal (bal3_trits_add '- '0 '(0 s)) '(0 - s))
(assert-equal (bal3_trits_add '- '+ '(- s)) '(0 - s))
(assert-equal (bal3_trits_add '0 '- '(0 s)) '(0 - s))
(assert-equal (bal3_trits_add '0 '0 '(- s)) '(0 - s))
(assert-equal (bal3_trits_add '+ '- '(- s)) '(0 - s))
(assert-equal (bal3_trits_add '- '0 '(+ s)) '(0 0 s))
(assert-equal (bal3_trits_add '- '+ '(0 s)) '(0 0 s))
(assert-equal (bal3_trits_add '0 '- '(+ s)) '(0 0 s))
(assert-equal (bal3_trits_add '0 '0 '(0 s)) '(0 0 s))
(assert-equal (bal3_trits_add '0 '+ '(- s)) '(0 0 s))
(assert-equal (bal3_trits_add '+ '0 '(- s)) '(0 0 s))
(assert-equal (bal3_trits_add '+ '- '(0 s)) '(0 0 s))
(assert-equal (bal3_trits_add '- '+ '(+ s)) '(0 + s))
(assert-equal (bal3_trits_add '0 '0 '(+ s)) '(0 + s))
(assert-equal (bal3_trits_add '0 '+ '(0 s)) '(0 + s))
(assert-equal (bal3_trits_add '+ '- '(+ s)) '(0 + s))
(assert-equal (bal3_trits_add '+ '0 '(0 s)) '(0 + s))
(assert-equal (bal3_trits_add '+ '+ '(- s)) '(0 + s))

(assert-equal (bal3_add '(0) '(-)) '(-))
(assert-equal (bal3_add '(+ 0) '(0 -)) '(+ -))
(assert-equal (bal3_add '(+ - - 0) '(+ 0 - -)) '(+ + + -))
(assert-equal (bal3_neg '(+ - - 0)) '(- + + 0))
(assert-equal (bal3_neg '(- + + - 0 0 0 - + + -))
                        '(+ - - + 0 0 0 + - - +))
(assert-equal (bal3_minus '(+ - - 0) '(+ 0 - -)) '(- 0 +))
