; In balanced ternary
(assert-equal (fib '(    0)) '(        0))
(assert-equal (fib '(    +)) '(        +))
(assert-equal (fib '(  + -)) '(        +))
(assert-equal (fib '(  + 0)) '(      + -))
(assert-equal (fib '(  + +)) '(      + 0))
(assert-equal (fib '(+ - -)) '(    + - -))
(assert-equal (fib '(+ - 0)) '(    + 0 -))
(assert-equal (fib '(+ - +)) '(    + + +))
(assert-equal (fib '(+ 0 -)) '(  + - + 0))
(assert-equal (fib '(+ 0 0)) '(  + + - +))
(assert-equal (fib '(+ 0 +)) '(+ - 0 0 +))
(assert-equal (fib '(+ + -)) '(+ 0 + 0 -))
; In binary
;(assert-equal (fib_bin '(         ())) '(                  ()))
;(assert-equal (fib_bin '(          t)) '(                   t))
;(assert-equal (fib_bin '(       t ())) '(                   t))
;(assert-equal (fib_bin '(       t  t)) '(                t ()))
;(assert-equal (fib_bin '(    t () ())) '(                t  t))
;(assert-equal (fib_bin '(    t ()  t)) '(             t ()  t))
;(assert-equal (fib_bin '(    t  t ())) '(          t () () ()))
;(assert-equal (fib_bin '(    t  t  t)) '(          t  t ()  t))
;(assert-equal (fib_bin '( t () () ())) '(       t ()  t ()  t))
;(assert-equal (fib_bin '( t () ()  t)) '(    t () () ()  t ()))
;(assert-equal (fib_bin '( t ()  t ())) '(    t  t ()  t  t  t))
;(assert-equal (fib_bin '( t  t ()  t)) '( t ()  t  t () ()  t))
