(assert-equal (fib '(0)) '(0))
(assert-equal (fib '(+)) '(+))
(assert-equal (fib '(+ -)) '(+))
(assert-equal (fib '(+ 0)) '(+ -))
(assert-equal (fib '(+ +)) '(+ 0))
(assert-equal (fib '(+ - -)) '(+ - -))
(assert-equal (fib '(+ - 0)) '(+ 0 -))
(assert-equal (fib '(+ - +)) '(+ + +))
(assert-equal (fib '(+ 0 -)) '(+ - + 0))
(assert-equal (fib '(+ 0 0)) '(+ + - +))
(assert-equal (fib '(+ 0 +)) '(+ - 0 0 +))
(assert-equal (fib '(+ + -)) '(+ 0 + 0 -))
