(assert-equal (fact '(0)) '(+))
(assert-equal (fact '(+)) '(+))
(assert-equal (fact '(+ -)) '(+ -))
(assert-equal (fact '(+ 0)) '(+ - 0))
(assert-equal (fact '(+ +)) '(+ 0 - 0))
(assert-equal (fact '(+ - -)) '(+ + + + 0))
(assert-equal (fact '(+ - 0)) '(+ 0 0 0 - 0 0))
(assert-equal (fact '(+ - +)) '(+ - + 0 - + - 0 0))
(assert-equal (fact '(+ 0 -)) '(+ - 0 0 + + 0 - + 0 0))
(assert-equal (fact '(+ 0 0)) '(+ - 0 0 + + 0 - + 0 0 0 0))
(assert-equal (fact '(+ 0 +)) '(+ - + - + + + 0 + - + 0 0 0 0))
